services:
  fisio-db:
    image: mariadb:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mariadb_data_dev:/var/lib/mysql
    networks:
      - fisio_network

volumes:
  mariadb_data_dev:

networks:
  fisio_network:
    driver: bridge

# Para rodar com um ambiente específico, use:
# docker-compose --env-file .env.dev up
# docker-compose --env-file .env.staging up